import Link from 'next/link';
import CareersBoard from '../../components/CareersBoard';
import { getJobs } from '../../lib/jobs';
import { createPageMetadata } from '../../lib/seo';

export const revalidate = 300;

export const metadata = createPageMetadata({ title: 'Software Engineering Careers at Csharptek', description: 'Explore opportunities to work on AI, product engineering, cloud platforms and software initiatives with Csharptek.', path: '/careers' });

export default async function CareersPage() {
  let jobs = [];
  try { jobs = await getJobs(); } catch (error) { console.error('JobPosting schema unavailable:', error.message); }
  const postings = jobs.map((job) => ({ '@context': 'https://schema.org', '@type': 'JobPosting', title: job.jobTitle, description: job.jobSummary || job.jobTitle, datePosted: job.createdOn ? new Date(job.createdOn).toISOString().slice(0, 10) : undefined, employmentType: 'FULL_TIME', hiringOrganization: { '@type': 'Organization', name: 'Csharptek', sameAs: 'https://www.csharptek.com' }, jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressLocality: job.location || 'Ranchi', addressCountry: 'IN' } }, url: 'https://www.csharptek.com/careers' }));
  return <>{postings.length > 0 && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(postings).replace(/</g, '\\u003c') }}/>}<section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Careers</div><span className="eyebrow">Careers at Csharptek</span><h1>Build useful technology with a team that owns the details.</h1><p>Join Csharptek to work on AI, product and cloud systems that solve real business problems—from the first design decisions through production.</p><div style={{marginTop:28}}><a className="button" href="#openings">View current openings <span aria-hidden="true">↓</span></a></div></div></section><section className="section"><div className="wrap"><div className="section-heading"><span className="eyebrow">A place to do meaningful engineering</span><h2>Bring your curiosity to real systems.</h2><p>Our work spans product engineering, AI, cloud platforms and healthcare workflows. We value clear thinking, thoughtful delivery and ownership of the details.</p></div><div className="solution-grid"><article className="content-panel"><span className="eyebrow">01 / Craft</span><h3>Build beyond prototypes</h3><p>Work through the integrations, quality and operating questions that make software useful in practice.</p></article><article className="content-panel"><span className="eyebrow">02 / Growth</span><h3>Learn across disciplines</h3><p>See how product, AI, data, cloud and user experience meet in a real delivery environment.</p></article><article className="content-panel"><span className="eyebrow">03 / Ownership</span><h3>Make your work count</h3><p>Take responsibility for clear outcomes, contribute ideas and keep improving how the system works.</p></article></div></div></section><section className="section section-dark" id="openings"><div className="wrap"><div className="section-heading"><span className="eyebrow eyebrow-light">Current opportunities</span><h2>Find a role where you can make a difference.</h2><p>Openings and application status are loaded from Csharptek’s careers service.</p></div><CareersBoard/></div></section></>;
}
