import Link from 'next/link';
import Icon from '../../../components/Icon';
import SolutionProof from '../../../components/SolutionProof';
import RelatedStories from '../../../components/RelatedStories';
import BrandArtwork from '../../../components/BrandArtwork';
import { createPageMetadata } from '../../../lib/seo';

export const metadata = createPageMetadata({ title: 'AI Product Engineering for SaaS Companies', description: 'Product engineering for SaaS teams adding AI capabilities, improving platform integrations and preparing software for Microsoft Marketplace commerce.', path: '/industries/technology-saas' });

export default function TechnologySaasPage() {
  return <><section className="page-hero"><div className="wrap page-hero-art-inner"><div className="page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Industries<span>/</span>Technology & SaaS</div><span className="eyebrow">Technology & SaaS</span><h1>Make your next product capability work in the product you already have.</h1><p>Extend established SaaS products with AI, integrations, cloud improvements and the commerce infrastructure behind growth.</p><div style={{marginTop:28}}><Link className="button" href="/contact?initiative=AI%20product">Discuss a product initiative <Icon name="arrow" size={16}/></Link></div></div><BrandArtwork slug="industry-technology-saas"/></div></section><section className="section"><div className="wrap content-grid"><div><span className="eyebrow">Product and platform work</span><h2>Build the feature, integration or platform layer that moves you forward.</h2><p>We partner with product and engineering leaders on AI capabilities, product workflows, cloud foundations and the technical requirements of SaaS commercialization.</p><ul className="check-list">{['AI assistants and product workflows','Product APIs and system integration','Multi-tenant SaaS architecture','Microsoft Marketplace fulfillment and metering','Cloud modernization and delivery'].map((x)=><li key={x}><Icon name="check" size={16}/>{x}</li>)}</ul></div><aside className="content-panel"><span className="eyebrow">Built around your roadmap</span><h3>Engineering that fits the product</h3><p>Start with a customer problem or product objective, then shape the architecture and delivery path around your users and existing system.</p><div className="tag-list"><span>AI products</span><span>SaaS</span><span>Azure</span><span>Marketplace</span></div><Link className="button button-dark" href="/solutions/ai-product-engineering">Explore AI product engineering <Icon name="arrow" size={15}/></Link></aside></div></section><SolutionProof slug="ai-product-engineering"/><RelatedStories slugs={['virilocity','image-to-video','landminer']} title="Product and platform engineering in practice" intro="Explore related examples across AI-enabled products and SaaS commerce."/><section className="section-tight"><div className="wrap"><Link className="text-link" href="/services/marketplace">Explore Microsoft Marketplace engineering <Icon name="arrow" size={15}/></Link></div></section></>;
}
