import Link from 'next/link';
import Icon from '../../../components/Icon';
import SolutionProof from '../../../components/SolutionProof';

export const metadata = { title: 'Technology & SaaS Engineering', description: 'AI product engineering and Microsoft Marketplace implementation for technology and SaaS companies.' };

export default function TechnologySaasPage() {
  return <><section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Industries<span>/</span>Technology & SaaS</div><span className="eyebrow">Technology & SaaS</span><h1>Make your next product capability work in the product you already have.</h1><p>Extend established SaaS products with AI, integrations, cloud improvements and the commerce infrastructure behind growth.</p><div style={{marginTop:28}}><Link className="button" href="/contact?initiative=AI%20product">Discuss a product initiative <Icon name="arrow" size={16}/></Link></div></div></section><section className="section"><div className="wrap content-grid"><div><span className="eyebrow">Product and platform work</span><h2>Build the feature, integration or platform layer that moves you forward.</h2><p>We partner with product and engineering leaders on AI capabilities, product workflows, cloud foundations and the technical requirements of SaaS commercialization.</p><ul className="check-list">{['AI assistants and product workflows','Product APIs and system integration','Multi-tenant SaaS architecture','Microsoft Marketplace fulfillment and metering','Cloud modernization and delivery'].map((x)=><li key={x}><Icon name="check" size={16}/>{x}</li>)}</ul></div><aside className="content-panel"><span className="eyebrow">Built around your roadmap</span><h3>Engineering that fits the product</h3><p>Start with a customer problem or product objective, then shape the architecture and delivery path around your users and existing system.</p><div className="tag-list"><span>AI products</span><span>SaaS</span><span>Azure</span><span>Marketplace</span></div></aside></div></section><SolutionProof slug="ai-product-engineering" /></>;
}
