const nextConfig = {
  reactStrictMode: true,
  images: {
    qualities: [75, 95],
  },
  async redirects() {
    return [
      { source: '/products/convosphere', destination: '/products', permanent: false },
      { source: '/products/interview-scheduler', destination: '/products', permanent: false },
      { source: '/portfolio', destination: '/case-studies', permanent: true },
      { source: '/casestudy/:slug*', destination: '/case-studies', permanent: true },
      { source: '/case-study/:slug*', destination: '/case-studies', permanent: true },
      { source: '/services/ai-integration', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/services/ai-voice', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/services/prompt-engineering', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/services/web-mobile', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/services/mvp-vibe', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/services/crm-productivity', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/services/cloud-devops', destination: '/azure-app-modernization-services', permanent: true },
      { source: '/services/support', destination: '/contact', permanent: true },
      { source: '/services', destination: '/solutions', permanent: true },
      { source: '/we-are-hiring', destination: '/careers', permanent: true },
      { source: '/software-trainee', destination: '/careers', permanent: true },
      { source: '/project-manager', destination: '/careers', permanent: true },
      { source: '/it-staffing', destination: '/careers', permanent: true },
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/healthcare-software-development', destination: '/industries/healthcare', permanent: true },
      { source: '/e-learning-solutions', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/mobile-app-development', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/azure-ai-service', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/ai-development-services', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/chatbot-development', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/cloud-consulting-services', destination: '/azure-app-modernization-services', permanent: true },
      { source: '/services/azure-mobile-applications', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/azure-integration-developer', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/cloud-migration-assesment-and-planning-services', destination: '/azure-app-modernization-services', permanent: true },
      { source: '/advance-technological-solutions', destination: '/solutions', permanent: true },
      { source: '/create-connected-manufacturing-experiences', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/chat-gpt', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/service-chat-gpt', destination: '/solutions/ai-production-engineering', permanent: true },
      { source: '/testing-and-qa-services', destination: '/solutions', permanent: true },
      { source: '/smarter-financial-solutions', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/react-developer', destination: '/careers', permanent: true },
      { source: '/senior-java-developer', destination: '/careers', permanent: true },
      { source: '/job-details/:id*', destination: '/careers', permanent: true },
      { source: '/Home/Index2', destination: '/', permanent: true },
      { source: '/Home/:slug*', destination: '/', permanent: true },
      { source: '/News/:slug*', destination: '/', permanent: true },
      { source: '/Srevices/:slug*', destination: '/solutions', permanent: true },
      { source: '/Recruitment/:slug*', destination: '/careers', permanent: true },
      { source: '/industries/marketing', destination: '/industries', permanent: true },
      { source: '/industries/pet-care', destination: '/industries/healthcare', permanent: true },
      { source: '/matchmaking-site-azure-devops-case-study', destination: '/case-studies', permanent: true },
      { source: '/patient-care-azure-ai-case-study', destination: '/case-studies', permanent: true },
      { source: '/bytehealthy-home-made-food-delivery-app', destination: '/case-studies', permanent: true },
      { source: '/real-estate-software-development', destination: '/industries/technology-saas', permanent: true },
      { source: '/industries/education', destination: '/industries', permanent: true },
      { source: '/industries/realestate', destination: '/industries', permanent: true },
      { source: '/industries/petcare', destination: '/industries/healthcare', permanent: true },
      { source: '/industries/wellness', destination: '/industries/healthcare', permanent: true },
      { source: '/industries/automation', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/industries/crm', destination: '/solutions/intelligent-workflow-automation', permanent: true },
      { source: '/industries/marketplace', destination: '/services/marketplace', permanent: true },
      { source: '/software-products-development-solutions', destination: '/solutions/ai-product-engineering', permanent: true },
      { source: '/custom-mobile-app-development-services', destination: '/solutions/ai-product-engineering', permanent: true }
    ];
  }
};

export default nextConfig;
