import Link from 'next/link';
import Icon from '../../components/Icon';
import BrandArtwork from '../../components/BrandArtwork';
import SolutionCardArtwork from '../../components/SolutionCardArtwork';
import { solutions } from '../../data/site';
import { createPageMetadata } from '../../lib/seo';

export const metadata = createPageMetadata({ title: 'Technology Solutions for Established Companies', description: 'Explore AI production engineering, AI product development, workflow automation, healthcare technology, Azure modernization and Microsoft Marketplace services.', path: '/solutions' });

export default function SolutionsPage() {
  return <><section className="page-hero"><div className="wrap page-hero-art-inner"><div className="page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Solutions</div><span className="eyebrow">Start with the business initiative</span><h1>Engineering for what your business needs to move forward.</h1><p>From putting AI to work to modernizing the systems you already rely on, bring us the hard problem and we’ll build the right path through it.</p></div><BrandArtwork slug="solutions-index"/></div></section><section className="section"><div className="wrap"><div className="section-heading"><span className="eyebrow">Ways we help</span><h2>Technology solutions built around business outcomes.</h2><p>We help established companies take a defined initiative from technical uncertainty to a system their teams can use and operate. Each engagement starts with your users, existing systems, data and constraints, then connects product and engineering decisions to the outcome you need.</p></div><div className="solution-grid">{solutions.map((item) => <Link className="solution-card" key={item.slug} href={item.slug === 'application-cloud-modernization' ? '/azure-app-modernization-services' : item.slug === 'microsoft-marketplace-engineering' ? '/services/marketplace' : `/solutions/${item.slug}`}><SolutionCardArtwork slug={item.slug}/><div className="solution-top"><span className="solution-number">{item.number} / SOLUTION</span><span className="solution-card-icon"><Icon name={item.icon} size={19}/></span></div><h3>{item.title}</h3><p>{item.short}</p><span className="solution-link">Explore solution <Icon name="arrow" size={15}/></span></Link>)}</div><div className="content-grid" style={{ marginTop: 64 }}><div><span className="eyebrow">Find your starting point</span><h2>Match the challenge to the right engineering path.</h2><p>Choose a business initiative to explore how the work is approached, what systems it can touch and what a practical next step could look like. For technical building blocks, browse our <Link href="/capabilities">engineering capabilities</Link>; for industry context, see <Link href="/industries">industries we support</Link>.</p></div><aside className="content-panel"><span className="eyebrow">Related work</span><h3>See the engineering in practice</h3><p>Review selected <Link href="/case-studies">case studies</Link> for examples of product, AI, workflow and platform challenges. You can also explore recent <Link href="/blog">engineering insights</Link>.</p></aside></div></div></section></>;
}
