import Link from 'next/link';
import { leaders } from '../../data/leadership';

import { createPageMetadata } from '../../lib/seo';

export const metadata = createPageMetadata({ title: 'Csharptek Leadership Team', description: 'Meet the Csharptek leaders guiding software product engineering, AI delivery and application modernization.', path: '/leadership' });

export default function LeadershipPage() {
  return <><section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/about">Company</Link><span>/</span>Leadership</div><span className="eyebrow">Leadership</span><h1>Engineering leadership, close to the work.</h1><p>Csharptek’s leadership brings together company direction, solution architecture and product delivery across client initiatives.</p></div></section><section className="section"><div className="wrap">{leaders.length ? <div className="leader-grid">{leaders.map((l)=><article className="leader-card" key={l.name}>{l.photo && <img className="leader-photo" src={l.photo} alt={l.name}/>}<h3>{l.name}</h3><span className="role">{l.role}</span><p>{l.bio}</p>{l.linkedin && <p style={{marginTop:12}}><a className="text-link" href={l.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a></p>}</article>)}</div> : <div className="empty-state">Leadership profiles are being prepared. <Link className="text-link" href="/contact">Talk with our team</Link></div>}</div></section><section className="section-tight"><div className="wrap content-grid"><div><span className="eyebrow">Work with our team</span><h2>Bring the initiative behind the technology.</h2><p>Explore the engineering areas our team supports, then connect with us about your goals and constraints.</p><Link className="text-link" href="/solutions">Explore solutions <span aria-hidden="true">→</span></Link></div><div><Link className="button button-dark" href="/contact">Discuss your initiative</Link></div></div></section></>;
}
