import Link from 'next/link';
import Icon from '../../components/Icon';
import RelatedStories from '../../components/RelatedStories';
import BrandArtwork from '../../components/BrandArtwork';

export const metadata = { title: 'Industries', description: 'Csharptek engineering for healthcare and technology companies, from clinical workflow automation to AI product and SaaS marketplace delivery.', alternates: { canonical: '/industries' } };

export default function IndustriesPage() {
  return <>
    <section className="page-hero"><div className="wrap page-hero-art-inner"><div className="page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Industries</div><span className="eyebrow">Context shapes the solution</span><h1>Engineering that fits the environment it has to serve.</h1><p>We bring product, AI and workflow engineering to industries where the data, users, integrations and operating details matter. Start with the context your team knows best.</p></div><BrandArtwork slug="industries-index"/></div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><span className="eyebrow">Explore industry context</span><h2>Start with the workflows and users you need to support.</h2><p>Industry experience helps connect technical choices to the realities of care delivery and software product operations.</p></div><div className="solution-grid"><Link className="solution-card" href="/industries/healthcare"><span className="eyebrow">Healthcare</span><h3>Build smarter healthcare workflows.</h3><p>Clinical documentation, intake, referrals, workforce coordination and healthcare product AI.</p><span className="solution-link">Explore healthcare <Icon name="arrow" size={15}/></span></Link><Link className="solution-card" href="/industries/technology-saas"><span className="eyebrow">Technology & SaaS</span><h3>Extend the products your customers rely on.</h3><p>AI capabilities, product workflows, platform integrations and Marketplace commerce.</p><span className="solution-link">Explore technology & SaaS <Icon name="arrow" size={15}/></span></Link></div></div></section>
    <section className="section section-tint"><div className="wrap content-grid"><div><span className="eyebrow">Connect context to capability</span><h2>Industry work often crosses product, AI and operations.</h2><p>Healthcare initiatives may join clinical documentation, telephony, intake and workforce coordination. SaaS initiatives may combine product experience, AI, identity, billing and Marketplace fulfillment. The right starting point depends on the workflow, not the trend.</p></div><aside className="content-panel"><span className="eyebrow">Explore solutions</span><h3>Choose a related engineering path</h3><ul className="check-list"><li><Icon name="check" size={16}/><Link href="/solutions/healthcare-ai-automation">Healthcare AI and automation</Link></li><li><Icon name="check" size={16}/><Link href="/solutions/ai-product-engineering">AI product engineering</Link></li><li><Icon name="check" size={16}/><Link href="/solutions/intelligent-workflow-automation">Intelligent workflow automation</Link></li><li><Icon name="check" size={16}/><Link href="/services/marketplace">Microsoft Marketplace engineering</Link></li></ul><Link className="text-link" href="/capabilities">Browse engineering capabilities <Icon name="arrow" size={15}/></Link></aside></div></section>
    <RelatedStories slugs={['woundmedix', 'medical-documentation', 'virilocity', 'payautomation']} title="Industry context, grounded in delivered work" intro="These anonymized stories connect healthcare operations and SaaS product challenges to the engineering behind them."/>
  </>;
}
