import Link from 'next/link';
import Icon from '../../components/Icon';
import { products } from '../../data/products';
import RelatedStories from '../../components/RelatedStories';

export const metadata = { title: 'Csharptek Products', description: 'Explore products from Csharptek, including TekDial and TekSocial, built from our own engineering work.', alternates: { canonical: '/products' } };

export default function ProductsPage() {
  return <>
    <section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Products</div><span className="eyebrow">Products from Csharptek</span><h1>Purpose-built products for connected work.</h1><p>Explore TekDial for voice workflows and TekSocial for social publishing. Each product grows from Csharptek’s product and AI engineering work.</p></div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><span className="eyebrow">Choose by workflow</span><h2>Start with the work your team needs to improve.</h2><p>Review the current product capabilities, then follow the related engineering path if your need involves a wider platform or integration.</p></div><div className="solution-grid">{products.map((product, i)=><Link className="solution-card" href={`/products/${product.slug}`} key={product.slug}><div className="solution-top"><span className="solution-number">0{i+1} / PRODUCT</span><span className="solution-card-icon"><Icon name={['flow','spark'][i] || 'layers'} size={19}/></span></div><h3>{product.name}</h3><p>{product.description}</p><span className="solution-link">Explore {product.name} <Icon name="arrow" size={15}/></span></Link>)}</div></div></section>
    <section className="section section-tint"><div className="wrap content-grid"><div><span className="eyebrow">Built around real workflows</span><h2>Products and services can share the same engineering foundation.</h2><p>Some teams need a ready product. Others need a capability designed into an existing application. Csharptek’s product engineering work connects the product experience to its data, integrations, identity and operations.</p><Link className="text-link" href="/solutions/ai-product-engineering">Explore AI product engineering <Icon name="arrow" size={15}/></Link></div><aside className="content-panel"><span className="eyebrow">Need something tailored?</span><h3>Explore the engineering paths</h3><ul className="check-list"><li><Icon name="check" size={16}/><Link href="/solutions/healthcare-ai-automation">Healthcare AI and workflow automation</Link></li><li><Icon name="check" size={16}/><Link href="/solutions/intelligent-workflow-automation">Intelligent workflow automation</Link></li><li><Icon name="check" size={16}/><Link href="/capabilities/data-integrations">Data and systems integration</Link></li></ul><Link className="button button-dark" href="/contact?initiative=Product%20inquiry">Discuss your product needs <Icon name="arrow" size={15}/></Link></aside></div></section>
    <RelatedStories slugs={['woundmedix', 'virilocity', 'image-to-video']} title="See related product and workflow engineering" intro="Explore projects that connect voice, AI product workflows and integrated operations."/>
  </>;
}
