import Link from 'next/link';
import Icon from '../../../components/Icon';
import SolutionProof from '../../../components/SolutionProof';

export const metadata = { title: 'Healthcare AI & Workflow Automation', description: 'Production-minded healthcare AI, product engineering and workflow automation for clinical and operational teams that need reliable, well-integrated systems.', alternates: { canonical: '/industries/healthcare' } };

export default function HealthcarePage() {
  return <><section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Industries<span>/</span>Healthcare</div><span className="eyebrow">Healthcare technology</span><h1>Build smarter healthcare workflows with production AI.</h1><p>Reduce administrative friction, connect operational workflows and integrate useful AI into healthcare systems and products.</p><div style={{marginTop:28}}><Link className="button" href="/contact?initiative=Healthcare">Discuss a healthcare initiative <Icon name="arrow" size={16}/></Link></div></div></section><section className="section"><div className="wrap content-grid"><div><span className="eyebrow">Where we can help</span><h2>Technology around the work of care.</h2><p>Healthcare systems operate across clinical, administrative and workforce processes. We engineer software that respects those real workflows and connects the systems around them.</p><ul className="check-list">{['Medical documentation workflows','Referral and intake automation','Healthcare product AI','Scheduling and workforce workflows','Patient communication and integrations'].map((x)=><li key={x}><Icon name="check" size={16}/>{x}</li>)}</ul></div><aside className="content-panel"><span className="eyebrow">Build with care</span><h3>Useful, grounded engineering</h3><p>We focus on workflow and product engineering, with appropriate attention to privacy, reliability, review and the boundaries of AI in a healthcare setting.</p><div className="tag-list"><span>Clinical documentation</span><span>Workflow automation</span><span>Product engineering</span><span>Data integrations</span></div></aside></div></section><SolutionProof slug="healthcare-ai-automation" /></>;
}
