import Link from 'next/link';
import Icon from '../../components/Icon';
import { capabilities } from '../../data/capabilities';

export const metadata = { title: 'Engineering Capabilities', description: 'Csharptek engineering capabilities across AI and LLMs, product engineering, Azure, .NET, cloud and DevOps, data and system integrations.', alternates: { canonical: '/capabilities' } };

export default function CapabilitiesPage() {
  return <>
    <section className="page-hero"><div className="wrap page-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>Capabilities</div><span className="eyebrow">The engineering behind the outcome</span><h1>Depth across the systems your initiative depends on.</h1><p>Connect the capabilities you need to the solution, product and operating environment you already have. We bring architecture, implementation and operational thinking together around the goal.</p></div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><span className="eyebrow">Explore by engineering need</span><h2>Choose the technical depth your initiative calls for.</h2><p>Capabilities can be engaged as a focused workstream or combined across a product, AI, workflow or modernization program.</p></div><div className="solution-grid">{capabilities.map((item)=><Link className="solution-card" href={`/capabilities/${item.slug}`} key={item.slug}><span className="eyebrow">Engineering capability</span><h3>{item.title}</h3><p>{item.description}</p><span className="solution-link">Explore capability <Icon name="arrow" size={15}/></span></Link>)}</div></div></section>
    <section className="section section-tint"><div className="wrap content-grid"><div><span className="eyebrow">Capabilities work together</span><h2>Connect specialist skills to a complete business outcome.</h2><p>An AI feature may also need product architecture, data access, identity, cloud operations and user review. A workflow automation project may depend on APIs, voice, CRM data and clear escalation to a person. We make those dependencies visible before they become delivery surprises.</p></div><aside className="content-panel"><span className="eyebrow">Start with the initiative</span><h3>Find the right solution path</h3><ul className="check-list"><li><Icon name="check" size={16}/><Link href="/solutions/ai-production-engineering">Put AI into production</Link></li><li><Icon name="check" size={16}/><Link href="/solutions/ai-product-engineering">Extend an existing product</Link></li><li><Icon name="check" size={16}/><Link href="/solutions/intelligent-workflow-automation">Connect a complex workflow</Link></li><li><Icon name="check" size={16}/><Link href="/azure-app-modernization-services">Modernize an application or cloud platform</Link></li></ul><Link className="text-link" href="/case-studies">See related engineering stories <Icon name="arrow" size={15}/></Link></aside></div></section>
  </>;
}
